#!/bin/bash

if [ -z $1 ]; then
	echo "Need at least one argument."
	echo "hostname or ip address of target pkeet."
	echo ""
	exit 1
fi
echo "Type what you wish, Ctrl+C to send the total message."
echo "Run chat again to start a new message."
echo ""
nc $1 1337
